"""empty message

Revision ID: 414d84a4c598
Revises: c609d43f5781
Create Date: 2022-09-24 15:59:41.823082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '414d84a4c598'
down_revision = 'c609d43f5781'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'price',
               existing_type=sa.Float(precision=10),
               type_=sa.REAL(),
               existing_nullable=False)
    # ### end Alembic commands ###
