"""empty message

<<<<<<<< HEAD:migrations/versions/a15358bdfee2_.py
Revision ID: a15358bdfee2
Revises: f5d6f40369a6
Create Date: 2022-10-07 03:00:13.044739
========
Revision ID: fed00c999abf
Revises: e70c2c3d9e86
Create Date: 2022-10-11 00:40:23.207476
>>>>>>>> 86577469e5776e0169df59b0a62766e93d73050e:migrations/versions/fed00c999abf_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<<< HEAD:migrations/versions/a15358bdfee2_.py
revision = 'a15358bdfee2'
down_revision = 'f5d6f40369a6'
========
revision = 'fed00c999abf'
down_revision = 'e70c2c3d9e86'
>>>>>>>> 86577469e5776e0169df59b0a62766e93d73050e:migrations/versions/fed00c999abf_.py
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_detail', 'price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10),
               existing_nullable=False)
    op.alter_column('product', 'price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'price',
               existing_type=sa.Float(precision=10),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('order_detail', 'price',
               existing_type=sa.Float(precision=10),
               type_=sa.REAL(),
               existing_nullable=False)
    # ### end Alembic commands ###
