"""empty message

<<<<<<<< HEAD:migrations/versions/bcc3a956bf04_.py
Revision ID: bcc3a956bf04
Revises: 7fe53fcfeb10
Create Date: 2022-10-09 03:20:14.391562
========
Revision ID: c2748486cbe4
Revises: 555ee98c9a7f
Create Date: 2022-10-10 23:06:23.833132
>>>>>>>> 94f5e6540711e6beac0cf74857e039fada2d98f7:migrations/versions/c2748486cbe4_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<<< HEAD:migrations/versions/bcc3a956bf04_.py
revision = 'bcc3a956bf04'
down_revision = '7fe53fcfeb10'
========
revision = 'c2748486cbe4'
down_revision = '555ee98c9a7f'
>>>>>>>> 94f5e6540711e6beac0cf74857e039fada2d98f7:migrations/versions/c2748486cbe4_.py
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_detail', 'price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10),
               existing_nullable=False)
    op.alter_column('product', 'price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'price',
               existing_type=sa.Float(precision=10),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('order_detail', 'price',
               existing_type=sa.Float(precision=10),
               type_=sa.REAL(),
               existing_nullable=False)
    # ### end Alembic commands ###
