"""empty message

Revision ID: d7f5abd76d60
Revises: cae65ed2eac6
Create Date: 2022-10-10 22:13:25.753351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7f5abd76d60'
down_revision = 'cae65ed2eac6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_detail', 'price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10),
               existing_nullable=False)
    op.alter_column('product', 'price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'price',
               existing_type=sa.Float(precision=10),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('order_detail', 'price',
               existing_type=sa.Float(precision=10),
               type_=sa.REAL(),
               existing_nullable=False)
    # ### end Alembic commands ###
